### ISSUE TITLE
Frequent discrepancy between statewise and national details on MoHFW

### ISSUE THREAD

**Issue by raptor419** [amodm/api-covid19-in#10]
There is a frequent discrepancy between statewise and national details on MoHFW.
Namely, the top displays total no of confirmed currently. Perhaps the summary could display the top value and the regional data the statewise data.

**Comment by amodm** [comment]
Can you elaborate? Where's the discrepancy? In the API, I calculate the total on my own.

**Comment by raptor419** [comment]
The total no of cases here as a national summary is 415
![image](https://user-images.githubusercontent.com/30626026/77306096-27f3f500-6d1d-11ea-99d6-ff6cff425db9.png)
The total no of cases calculated here and in the API is Confirmedindian+confirmedforeign= 349+41 = 390
![image](https://user-images.githubusercontent.com/30626026/77306067-1a3e6f80-6d1d-11ea-8041-dd0303a9481c.png)

The summary part of the API JSON should have the national figure of 415, I think.

**Comment by amodm** [comment]
Makes sense. Additionally, I'll include an `locationNotIdentified` count in summary so that at least there's some information about it

**Comment by raptor419** [comment]
Additionally, I'd like to thank you for your efforts. I've been making a Covid Tracker similar to covid19india.org but sourced for MoHFW for awareness efforts of our research lab.
https://agile-escarpment-47244.herokuapp.com/

Thank you for the work you've been doing for Covid dev.

**Comment by amodm** [comment]
Glad to hear. This is done.
