### ISSUE TITLE
Daily stats summary of current date and final summary is not matching

### ISSUE THREAD

**Issue by imsurajsharma** [amodm/api-covid19-in#11]
final summary from this API -https://api.rootnet.in/covid19-in/stats/latest
and current date summary from this API-https://api.rootnet.in/covid19-in/stats/daily

are not equal. I think both should be equal.

As of today, 26 March 2020, the  total confirmed cases in this api (https://api.rootnet.in/covid19-in/stats/latest) is 649 and total confirmed cases from this AP (https://api.rootnet.in/covid19-in/stats/daily) is 679.

**Comment by amodm** [comment]
Yes, they should

**Comment by imsurajsharma** [comment]
then change it.

**Comment by amodm** [comment]
Fixed. Looking at the logs, originally [MoHFW](https://www.mohfw.gov.in) published Goa's number as 33, and later changed it to 3. The refresh script doesn't modify a snapshot once it is set, which is why this happened.
