### ISSUE TITLE
Error in the response data fro the API  https://api.rootnet.in/covid19-in/unofficial/covid19india.org 

### ISSUE THREAD

**Issue by AravinthanPraba007** [amodm/api-covid19-in#13]
When I hit these URL 
https://api.rootnet.in/covid19-in/unofficial/covid19india.org
The response data is empty 
"summary":{"total":0},"rawPatientData":[]},"

But till yesterday it was working fine
Can you please check what went wrong.

**Comment by amodm** [comment]
Thx for notifying. The patient number header was deleted. I've hacked it to fix it for now, and working with the covid19india.org team to get the sheet fixed.
