### ISSUE TITLE
Incomplete History Data

### ISSUE THREAD

**Issue by Sidd27** [amodm/api-covid19-in#15]
Hi 
Below API 
https://api.rootnet.in/covid19-in/unofficial/covid19india.org/statewise/history
Has data only from 2020-03-24

Needed the data from atleast 2020-03-10

**Comment by amodm** [comment]
Fixed. But I have the data only from 2020-03-14 onwards, as that's when covid19india.org's sheet was created

**Comment by Sidd27** [comment]
Ok Cool Thanks
