### ISSUE TITLE
description + GraphQL

### ISSUE THREAD

**Issue by tomByrer** [amodm/api-covid19-in#2]
Hi, you have good work here!
I am trying to promote your work, but seems some scrapers like [this Awesome List](https://github.com/soroushchehresa/awesome-coronavirus#api) use it, so a better description could help others.  Could you change description to something like:
`COVID Rest API for India data, using Cloudflare Workers`
?

Also, if you want to add an GraphQL endpoint, this repo might be of help; uses `apollo-server-cloudflare` 
https://github.com/COVID19Tracking/covid-tracking-api

I'll add you to my awesome list shortly:
https://github.com/tomByrer/awesome-cloudflare-workers#boss

Thanks for all your hard work!

**Comment by amodm** [comment]
Added that description. Will look at the GraphQL ep later.

**Comment by ret394** [comment]
this project is great, only JSON output. no silly frills. exactly what I need.

thanks. have a nice day. keep up the good work. 👍

[ret394](https://github.com/ret394)

**Comment by amodm** [comment]
Archiving this repo now.
