### ISSUE TITLE
Status not matching using raw patient data

### ISSUE THREAD

**Issue by k-pratik** [amodm/api-covid19-in#21]
I am using this API https://api.rootnet.in/covid19-in/unofficial/covid19india.org to get all details. In the response when I iterate in rawPatientData to get all status and their count I get following result:
"MIGRATED":1,"HOSPITALIZED":1068,"DECEASED":18,"RECOVERED":52

This count is not matching with actual count which I see on dashbord.

Thank you

**Comment by amodm** [comment]
What's the actual count that you see on the API vs the dashboard?

**Comment by k-pratik** [comment]
By API: 
"countByStatus":{"":10,"MIGRATED":1,"HOSPITALIZED":1102,"DECEASED":18,"RECOVERED":52}

On Dashboard:
DECEASED: 29, RECOVERED:102, ACTIVE:1042, CONFIRMED: 1173

**Comment by amodm** [comment]
@k-pratik the recovered and death reports has not always been traceable to raw patient data, so doesn't reflect appropriately. The covid19india.org community has been maintaining the two separately.

If you look at the data from https://api.rootnet.in/covid19-in/unofficial/covid19india.org/statewise you should see them matching up

**Comment by amodm** [comment]
For history, you can look up https://api.rootnet.in/covid19-in/unofficial/covid19india.org/statewise/history
