### ISSUE TITLE
lastOriginUpdate Is Wrong in Offcial API

### ISSUE THREAD

**Issue by Sidd27** [amodm/api-covid19-in#23]
![image](https://user-images.githubusercontent.com/17669399/78065862-92f29b00-73b1-11ea-931e-46ebb6dd734f.png)
API https://api.rootnet.in/covid19-in/stats/history
Last Origin update date is coming as "lastOriginUpdate": "1970-01-01T00:00:00.000Z"

**Comment by amodm** [comment]
Yeah, the MoHFW modified their timestamp last night. 0be882b should fix it
