### ISSUE TITLE
Interpretation of statewise count in latest API

### ISSUE THREAD

**Issue by siddharthsrivastava** [amodm/api-covid19-in#25]
Hi

In the API: https://api.rootnet.in/covid19-in/stats/latest, the confirmed count for Delhi is shown as 502, and 1 foreigner. Though the total count on MoHFW at the moment is 503 with no specific details on foreigner count.  Same case is with Goa and a few other states. Is the total count for state has to be interpreted as confirmedIndianCases+ForeignCases ? Just confused as MoHFW doesn't seem to provide separate data for the two now.

**Comment by amodm** [comment]
This is a mess unfortunately. As you know, MoHFW used to publish the data separately for Indians & Foreigners, for each state. But in the more recent times, it has stopped giving this breakdown. I've avoided breaking the API's contract by hacking it [like this](https://github.com/amodm/api-covid19-in/blob/master/refresh.js#L141) deals with that logic. But clearly this logic seems to be running into its limits. I'll have to figure out how to deal with this without breaking the API's contract. Until then, please rely only on the total numbers for each state, not the breakdown.

**Comment by amodm** [comment]
Total foreign count is now shown correctly, though it won't add up to individual states' foreign counts as that breakdown isn't available anymore
