### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by pragatiutrack** [amodm/api-covid19-in#26]
Can you please let me know which maps you are using please.

**Comment by amodm** [comment]
I'm not using any maps

**Comment by pragatiutrack** [comment]
> 
> 
> I'm not using any maps

hi Thanks,
You actually did a great JOB in plotting those records on map state wise and district wise. Can you please let me how it can be done as we would need this for a different application. We will pay for the same.

**Comment by amodm** [comment]
@pragatiutrack this is a pure data API. There's plenty of maps API you can find on the web. [Google](https://developers.google.com/maps/documentation/javascript/tutorial) and [MapBox](https://www.mapbox.com) are two of them.

Also, please stop creating additional issues for these questions. Use StackOverflow & Google
