### ISSUE TITLE
In the unofficial patient tracking data API, gender is defaulted to "female"

### ISSUE THREAD

**Issue by rohanrmallya** [amodm/api-covid19-in#28]
**Problem**
Using [this](https://api.rootnet.in/covid19-in/unofficial/covid19india.org) route, I can see that the data for gender is defaulted to female. This is incorrect as in the [patient-db](bit.ly/patientdb), there are rows that have a blank cell for gender where gender is unknown.

Case in point, patient with ID 2 does not have a gender.

![patientdb](https://user-images.githubusercontent.com/1576127/78638082-48997e80-78c9-11ea-8dcb-c07e14a3d56e.png)

But API response marks the patient as female

![OnPaste 20200407-121252](https://user-images.githubusercontent.com/1576127/78638099-4f27f600-78c9-11ea-88f8-0f4808de1f07.png)

**Analysis**
I can see that while we are fetching the data we are assigning gender as male only by checking the first letter of the cell. ([src](https://github.com/amodm/api-covid19-in/blob/0be882be882e872a57377a9830cd83978ae81505/data/unofficial/index.js#L21))

**Possible Solution**

Gender should be empty in the response, if gender is empty in the patient-db

**Comment by amodm** [comment]
Agreed. Care to raise a PR?

**Comment by rohanrmallya** [comment]
> Agreed. Care to raise a PR?

Sure! :+1:

**Comment by amodm** [comment]
Thx for the fix.
