### ISSUE TITLE
Today's Data is not coming in history API

### ISSUE THREAD

**Issue by Sidd27** [amodm/api-covid19-in#31]
<img width="651" alt="Screenshot 2020-04-12 at 6 32 22 PM" src="https://user-images.githubusercontent.com/17669399/79069453-f5ba2f80-7ceb-11ea-8e0e-d415556dc357.png">
This is the last element in history key of JSON
But the lastRefreshed date is coming of Today

This is the API https://api.rootnet.in/covid19-in/unofficial/covid19india.org/statewise/history

**Comment by Sidd27** [comment]
But the lastRefreshed date is coming of Today

**Comment by amodm** [comment]
Fixed. Thanks for reporting.
