### ISSUE TITLE
Mismatch in Numbers

### ISSUE THREAD

**Issue by maisonml** [amodm/api-covid19-in#33]
I pulled the numbers from your API, the overall count is shown as 13835, but in the John Hopkins database, the overall count is 14352. I pulled both numbers at 9.30 PM EST (17th Apr) or 7 AM IST (18th Apr). Can you please let me know the reason for this?

**Comment by amodm** [comment]
They might be pulling the data from an unofficial source (likely covid19india.org). Both are available here:

Official (MoHFW) data: https://api.rootnet.in/covid19-in/stats/latest
Covid19india.org data: https://api.rootnet.in/covid19-in/unofficial/covid19india.org/statewise

MoHFW data is updated twice a day by the officials, while Covid19india is a community curated data, so is more real time. The difference between the two changes over the day, from +ve to -ve

**Comment by amodm** [comment]
The full list of APIs is listed on README: https://github.com/amodm/api-covid19-in
