### ISSUE TITLE
Change in MoHFW table structure and null values

### ISSUE THREAD

**Issue by siddharthsrivastava** [amodm/api-covid19-in#35]
The total summary (official) is showing null values. The error seems to be due to change in MoHFW table with cases being transferred among states (230 as of now which appears as a state in the api output). 
![Screenshot_20200516-105004](https://user-images.githubusercontent.com/534879/82126878-37e3fe80-97cd-11ea-87f9-57cbba8cc693.png)

**Comment by amodm** [comment]
Thanks @siddharthsrivastava, for the lead on what's causing this.

**Comment by amodm** [comment]
This is fixed now.

**Comment by siddharthsrivastava** [comment]
Thanks for fixing.
