### ISSUE TITLE
Null deaths and recovered in daily api

### ISSUE THREAD

**Issue by siddharthsrivastava** [amodm/api-covid19-in#36]
The daily API is returning null for deaths and recovered on 16 May. This is caused due to an earlier issue caused by change in table structure of MoHFW. The state with loc:230 is causing this. 

![Screenshot_20200517-110355](https://user-images.githubusercontent.com/534879/82136761-7fe73d80-982e-11ea-80a4-3ff295813553.png)

**Comment by amodm** [comment]
Thanks for reporting. Fixed manually. Was related to #35 that you reported.

**Comment by siddharthsrivastava** [comment]
Thanks for fixing
