### ISSUE TITLE
Testing Data is not updated after 24th July, 2020

### ISSUE THREAD

**Issue by akashagl92** [amodm/api-covid19-in#39]
The API for testing data - Latest/History/Raw aren't updated after 24th July, 2020. Is there any alternative Web API to use instead to collect test related information.

**Comment by amodm** [comment]
@akashagl92 thanks for bringing this to my notice. This is now fixed.

**Comment by akashagl92** [comment]
Thank you! I am curious if there is any API with state specific testing data. Any lead might be helpful.

**Comment by amodm** [comment]
There's [a bunch of APIs](https://api.covid19india.org) that the covid19india team maintains. You can try looking for this data there as well.
