### ISSUE TITLE
Raw Data missing from 28th July 2020 to 31st July 2020

### ISSUE THREAD

**Issue by akashagl92** [amodm/api-covid19-in#40]
Raw Data from 2020-07-28 to 2020-07-31 missing in api https://api.rootnet.in/covid19-in/stats/history . Could you please help me on this one too? Although the test data is now correctly available till 1st August 2020.

Thank you!

**Comment by amodm** [comment]
This is fixed now as well. There was a gap of 4 days that got introduced when MoHFW changed its format (yet again). I've reintroduced that data from the wayback machine.

**Comment by akashagl92** [comment]
Thank you again! 

This change also seem to have impacted Kerala on 31st July 2020 by bringing the "totalConfirmed" down to 2203 from 21797 on 30th July 2020.

**Comment by amodm** [comment]
You're right. The data for 31st appears to have had a typo borrowed from the MoHFW data. It should've been 22303, but was 2203 instead. Looks like they continue to put in the data manually. Makes maintaining this API a nightmare to be honest.

**Comment by amodm** [comment]
I've fixed it for now.

**Comment by akashagl92** [comment]
Hey Amod,

Thank you! Appreciate the prompt response.

Regards,
Akash Agrawal
+91 9019207434
