### ISSUE TITLE
Data missing for Aug 31 and Sep 2

### ISSUE THREAD

**Issue by akashagl92** [amodm/api-covid19-in#44]
The json data is missing for Aug 31 and Sep 2.

**Comment by amodm** [comment]
In which api?

**Comment by akashagl92** [comment]
COVID19 - https://api.rootnet.in/covid19-in/stats/history

**Comment by amodm** [comment]
It seems to be there

```
me@lo:~$ curl -s https://api.rootnet.in/covid19-in/stats/history | jq '.data[] | select(.day=="2020-08-31") | .summary'
{
  "total": 3621245,
  "confirmedCasesIndian": 3621197,
  "confirmedCasesForeign": 48,
  "discharged": 2774801,
  "deaths": 64469,
  "confirmedButLocationUnidentified": 0
}
me@lo:~$ curl -s https://api.rootnet.in/covid19-in/stats/history | jq '.data[] | select(.day=="2020-09-02") | .summary'
{
  "total": 3769523,
  "confirmedCasesIndian": 3769475,
  "confirmedCasesForeign": 48,
  "discharged": 2901908,
  "deaths": 66333,
  "confirmedButLocationUnidentified": 0
}
```

**Comment by akashagl92** [comment]
Sorry for not being clear enough.


The data for 31st Aug is same as 30th Aug; Similarly, the data for 2nd Sept
is same as 1st Sept. I have shown the example of summaries from the API
below:




"day": "2020-08-31",

      "summary": {

        "total": 3621245,

        "confirmedCasesIndian": 3621197,

        "confirmedCasesForeign": 48,

        "discharged": 2774801,

        "deaths": 64469,

        "confirmedButLocationUnidentified": 0




"day": "2020-08-30",

      "summary": {

        "total": 3621245,

        "confirmedCasesIndian": 3621197,

        "confirmedCasesForeign": 48,

        "discharged": 2774801,

        "deaths": 64469,

        "confirmedButLocationUnidentified": 0



"day": "2020-09-01",

      "summary": {

        "total": 3769523,

        "confirmedCasesIndian": 3769475,

        "confirmedCasesForeign": 48,

        "discharged": 2901908,

        "deaths": 66333,

        "confirmedButLocationUnidentified": 0


"day": "2020-09-02",

      "summary": {

        "total": 3769523,

        "confirmedCasesIndian": 3769475,

        "confirmedCasesForeign": 48,

        "discharged": 2901908,

        "deaths": 66333,

        "confirmedButLocationUnidentified": 0


I hope this helps. Because of this, my code is failing to provide updated
info on states for 31st Aug and 2nd Sept.


Thank you!


Regards,

Akash.

**Comment by amodm** [comment]
Good find, @akashagl92. Fixed. I've also done an eyeballing of the data to check for any other duplicates. Looks good for now.

**Comment by akashagl92** [comment]
Thank you Amod!
