### ISSUE TITLE
Duplicate Data for few dates in Sept and Oct

### ISSUE THREAD

**Issue by akashagl92** [amodm/api-covid19-in#47]
**24th and 25th Sept**

"day": "2020-09-24",
      "summary": {
        "total": 5818570,
        "confirmedCasesIndian": 5818522,
        "confirmedCasesForeign": 48,
        "discharged": 4756164,
        "deaths": 92290,
        "confirmedButLocationUnidentified": 0
      },

"day": "2020-09-25",
      "summary": {
        "total": 5818570,
        "confirmedCasesIndian": 5818522,
        "confirmedCasesForeign": 48,
        "discharged": 4756164,
        "deaths": 92290,
        "confirmedButLocationUnidentified": 0

====================================
**1st and 2nd Oct**

 "day": "2020-10-01",
      "summary": {
        "total": 6394068,
        "confirmedCasesIndian": 6394020,
        "confirmedCasesForeign": 48,
        "discharged": 5352078,
        "deaths": 99773,
        "confirmedButLocationUnidentified": 0

"day": "2020-10-02",
      "summary": {
        "total": 6394068,
        "confirmedCasesIndian": 6394020,
        "confirmedCasesForeign": 48,
        "discharged": 5352078,
        "deaths": 99773,
        "confirmedButLocationUnidentified": 0

===================================
**4th and 5th Oct**

"day": "2020-10-04",
      "summary": {
        "total": 6623815,
        "confirmedCasesIndian": 6623767,
        "confirmedCasesForeign": 48,
        "discharged": 5586703,
        "deaths": 102685,
        "confirmedButLocationUnidentified": 0

"day": "2020-10-05",
      "summary": {
        "total": 6623815,
        "confirmedCasesIndian": 6623767,
        "confirmedCasesForeign": 48,
        "discharged": 5586703,
        "deaths": 102685,
        "confirmedButLocationUnidentified": 0

=================================
**7th and 8th Oct**

"day": "2020-10-07",
      "summary": {
        "total": 6835655,
        "confirmedCasesIndian": 6835607,
        "confirmedCasesForeign": 48,
        "discharged": 5827704,
        "deaths": 105526,
        "confirmedButLocationUnidentified": 0

"day": "2020-10-08",
      "summary": {
        "total": 6835655,
        "confirmedCasesIndian": 6835607,
        "confirmedCasesForeign": 48,
        "discharged": 5827704,
        "deaths": 105526,
        "confirmedButLocationUnidentified": 0

==================================
**11th and 12th Oct**

"day": "2020-10-11",
      "summary": {
        "total": 7120538,
        "confirmedCasesIndian": 7120490,
        "confirmedCasesForeign": 48,
        "discharged": 6149535,
        "deaths": 109150,
        "confirmedButLocationUnidentified": 0

 "day": "2020-10-12",
      "summary": {
        "total": 7120538,
        "confirmedCasesIndian": 7120490,
        "confirmedCasesForeign": 48,
        "discharged": 6149535,
        "deaths": 109150,
        "confirmedButLocationUnidentified": 0

**Comment by amodm** [comment]
Thanks for reporting this @akashagl92 

Fixed by averaging, as I don't have access to the raw data anymore (no archives), except for 2020-10-11. I've set up a cron job to retain the fetched sources of mohfw, so that in case this happens again, I don't have to rely on averaging.
