### ISSUE TITLE
Pair of Duplicates for 23rd and 24th Oct in covid19-stats API

### ISSUE THREAD

**Issue by akashagl92** [amodm/api-covid19-in#48]
Another pair of duplicates for 23rd and 24th Oct for https://api.rootnet.in/covid19-in/stats/history. Can we please fix this too?

{
      "day": "2020-10-23",
      "summary": {
        "total": 7814682,
        "confirmedCasesIndian": 7814634,
        "confirmedCasesForeign": 48,
        "discharged": 7016046,
        "deaths": 117956,
        "confirmedButLocationUnidentified": 0
      },

{
      "day": "2020-10-24",
      "summary": {
        "total": 7814682,
        "confirmedCasesIndian": 7814634,
        "confirmedCasesForeign": 48,
        "discharged": 7016046,
        "deaths": 117956,
        "confirmedButLocationUnidentified": 0
      },

**Comment by amodm** [comment]
An embarassingly long time to respond to this, but this was fixed.
