### ISSUE TITLE
Are the APIs still relevant for Covid-19 2nd Wave and what is the frequency at which it pulls data from Govt Database

### ISSUE THREAD

**Issue by censation** [amodm/api-covid19-in#50]
Are the APIs still relevant for Covid-19 2nd Wave and what is the frequency at which it pulls data from Govt Database

**Comment by amodm** [comment]
Yes, the counts API should still be relevant. Information is polled twice an hour, but usually the govt seems to update it once a day, so effectively it's once a day.
