### ISSUE TITLE
the beds data is not live its from 2018

### ISSUE THREAD

**Issue by RootAndroid58** [amodm/api-covid19-in#51]
Posted On: 24 JUL 2018 5:03PM by PIB Delhi
![image](https://user-images.githubusercontent.com/28777412/122634135-1e149980-d0fa-11eb-8176-2adffe2e06b9.png)

its too old data

**Comment by amodm** [comment]
The beds data isn't picked from the worldbank site. It's picked from a service exposed by @NirantK which uses PIB sources. You can see the relevant code [here](https://github.com/amodm/api-covid19-in/blob/master/refresh-hospital-beds.js#L138) and it's data is accessible [here](https://api.steinhq.com/v1/storages/5e732accb88d3d04ae0815ae/StateWiseHealthCapacity)

Or am I misunderstanding your concern?

**Comment by NirantK** [comment]
I believe the issue is stale since there has been no follow up in a week. Maybe you can go ahead and close it?
