### ISSUE TITLE
CORS ISSUE

### ISSUE THREAD

**Issue by moulsiri** [amodm/api-covid19-in#54]
while using this api I got cors issue please resolve it in server side.

**Comment by amodm** [comment]
What's the exact issue you're facing? The APIs already send `access-control-allow-origin: *` in response header.

**Comment by amodm** [comment]
@moulsiri I'll be closing this issue in next couple of days if no further details are available.

**Comment by moulsiri** [comment]
While calling this api with axios in react it is continuously giving CORS error so may be this issue will be resolved in backend .

**Comment by amodm** [comment]
Please double check if the CORS error is happening on a call to my api server, or some other URL. If you're sure that my api server is the problem, please share a fully working piece of code where this fails on CORS.

**Comment by moulsiri** [comment]
Ok I have checked it, right now I'm not facing any issue related to CORS , you may close this issue. Thanks!
